### ISSUE TITLE
File hoster

### ISSUE THREAD

**Issue by bafu** [numbersprotocol/MindBook#1]
This issue is used to host files by adding attachments, and is not a real issue.

---
![mindbook-ce-1](https://user-images.githubusercontent.com/292790/61634088-215f3a80-acc3-11e9-8793-62db8fe2775c.png)
![mindbook-ce-2](https://user-images.githubusercontent.com/292790/61634090-215f3a80-acc3-11e9-991a-5be0a24ab49d.png)
![mindbook-ce-3](https://user-images.githubusercontent.com/292790/61634091-21f7d100-acc3-11e9-8b3b-023c6df7f019.png)
![mindbook-ce-4](https://user-images.githubusercontent.com/292790/61634276-929eed80-acc3-11e9-9305-5f08ffc2a8d9.png)
![mindbook-ce-5](https://user-images.githubusercontent.com/292790/61634093-21f7d100-acc3-11e9-912f-0b2fe9961cae.png)
![mindbook-ce-6](https://user-images.githubusercontent.com/292790/61634963-1a392c00-acc5-11e9-9eb9-50eab11eb137.png)
![mindbook-ce-7](https://user-images.githubusercontent.com/292790/61634964-1a392c00-acc5-11e9-9f08-3be3b2f14740.png)
![mindbook-ce-8](https://user-images.githubusercontent.com/292790/61634965-1a392c00-acc5-11e9-92f0-63ce2997970a.png)

**Comment by seanwu1105** [comment]
![enable-extension-preview](https://user-images.githubusercontent.com/14951000/61637314-de549580-acc9-11e9-8b50-2f56fc940503.png)

![Screen Shot 2019-07-22 at 10 32 30 PM](https://user-images.githubusercontent.com/14951000/61641039-fbd92d80-acd0-11e9-8d24-44e203558c30.png)

![Screen Shot 2019-07-22 at 10 34 25 PM](https://user-images.githubusercontent.com/14951000/61641045-fe3b8780-acd0-11e9-8031-9a030d60d72b.png)

![Screen Shot 2019-07-22 at 10 34 35 PM](https://user-images.githubusercontent.com/14951000/61641049-00054b00-acd1-11e9-90ae-708a5344dab6.png)

![Screen Shot 2019-07-22 at 10 41 27 PM](https://user-images.githubusercontent.com/14951000/61641563-f203fa00-acd1-11e9-991b-3ad4a148d8fd.png)
